name: Update Repo

# Controls when the workflow will run
on:
  # run ever two hours
  schedule:
    - cron: 5 * * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: master-clean-arm32
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Run app update scripts
        run: |
          git config pull.twohead ort
          git config --global pull.twohead ort
          git remote add -f upstream "https://github.com/PolyMC/meta-polymc.git"
          git remote -v
          git branch --all
          git config --list
          git config user.email "30313089+Waoweens@users.noreply.github.com"
          git config user.name "Waoweens"
          git checkout master-clean-arm32
          git merge remotes/upstream/master -m "Sync with upstream - $(date)"
          git push
          
          git checkout master-clean
          git merge remotes/upstream/master -m "Sync with upstream - $(date)"
          git push
